apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-scoring-api
  labels:
    app: ml-scoring-api
spec:
  replicas: 2  # Número de pods a ejecutar
  selector:
    matchLabels:
      app: ml-scoring-api
  template:
    metadata:
      labels:
        app: ml-scoring-api
    spec:
      containers:
      - name: ml-scoring-api
        image: dachacond967/ml-scoring-api:latest  # Imagen Docker creada anteriormente
        ports:
        - containerPort: 8888  # Puerto que expone la aplicación dentro del contenedor
        env:
        - name: CONFIG_PATH  # Variable de entorno para la configuración
          value: "/app/src/config.yaml"
