apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-scoring-api
  labels:
    app: ml-scoring-api
spec:
  replicas: 1  # Número de pods a ejecutar
  selector:
    matchLabels:
      app: ml-scoring-api
  template:
    metadata:
      labels:
        app: ml-scoring-api
    spec:
      containers:
        - name: ml-scoring-api
          image: 796973493835.dkr.ecr.us-east-1.amazonaws.com/ml-scoring-api  # Imagen Docker desde Amazon ECR
          ports:
            - containerPort: 8888  # Puerto que expone la aplicación dentro del contenedor
          env:
            - name: CONFIG_PATH  # Variable de entorno para la configuración
              value: "/app/src/config.yaml"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: ecr-secret

