apiVersion: v1
kind: Service
metadata:
  name: ml-scoring-api-service
  namespace: produccion  # Especifica el namespace
spec:
  selector:
    app: ml-scoring-api  # Debe coincidir con las etiquetas del Deployment en produccion
  ports:
    - protocol: TCP
      port: 80           # Puerto accesible para usuarios externos
      targetPort: 8888   # Puerto interno del contenedor
      nodePort: 30000    # Puerto único para produccion
  type: NodePort          # Exposición en el puerto de un nodo
